### GET ALL
GET http://localhost:3000/api/producto

### POST
# @name createMarca
POST http://localhost:3000/api/producto
Content-Type: application/json

{
    "descripcion": "shampoo",
    "categoria": 1,
    "marcas": [1,2]
}

###ID
@id = {{createMarca.response.body.data.idProducto}}

### GET ONE
GET http://localhost:3000/api/producto/{{id}}

### PUT
PUT http://localhost:3000/api/producto/{{id}}
Content-Type: application/json

{
    "descripcion": "shampoo",
    "categoria": 1,
    "marcas": [2]
  
}

### POST to delete
# @name createItemToDelete
POST http://localhost:3000/api/producto
Content-Type: application/json

{
   "descripcion": "acoondicionador",
    "categoria": 1,
    "marcas": [1]
  
}

@idToDelete = {{createItemToDelete.response.body.data.idProducto}}

DELETE http://localhost:3000/api/producto/{{idToDelete}}