### obtener todos los descuento
GET http://localhost:3000/api/descuento

### obtener un descuento
GET http://localhost:3000/api/descuento/f47ac10b-58cc-4372-a567-0e02b2c3d479

### crear un nuevo descuento
POST http://localhost:3000/api/descuento
Content-Type: application/json

### modificar un descuento (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/descuento/5700ed7b-6f37-4c15-8828-49cd8c346968
Content-Type: application/json

### modificar un descuento (PATCH - recurso parcial)
PATCH http://localhost:3000/api/descuento/5700ed7b-6f37-4c15-8828-49cd8c346968
Content-Type: application/json

### borrar un descuento
DELETE http://localhost:3000/api/descuento/5700ed7b-6f37-4c15-8828-49cd8c346968