### GET ALL
GET http://localhost:3000/api/tono

### POST
# @name createMarca
POST http://localhost:3000/api/tono
Content-Type: application/json

{
    "nombre": "marron"
}

###ID
@id = {{createMarca.response.body.data.idTono}}

### GET ONE
GET http://localhost:3000/api/tono/{{id}}

### PUT
PUT http://localhost:3000/api/tono/{{id}}
Content-Type: application/json

{
    "nombre": "marron"
}

### POST2
# @name createTonoToDelete
POST http://localhost:3000/api/tono
Content-Type: application/json

{
    "nombre": "negro"
}

### DELETE
@idToDelete = {{createTonoToDelete.response.body.data.idTono}}
DELETE http://localhost:3000/api/tono/{{idToDelete}}