### GET ALL
GET http://localhost:3000/api/marca

### POST
# @name createMarca
POST http://localhost:3000/api/marca
Content-Type: application/json

{
    "nombre": "Loreal"
}

###ID
@id = {{createMarca.response.body.data.idMarca}}

### GET ONE
GET http://localhost:3000/api/marca/{{id}}

### PUT
PUT http://localhost:3000/api/marca/{{id}}
Content-Type: application/json

{
    "nombre": "Loreal"
}


### POST
# @name createMarcaToDelete
POST http://localhost:3000/api/marca
Content-Type: application/json

{
    "nombre": "Loreal"
}

### DELETE
@idToDelete = {{createMarcaToDelete.response.body.data.idMarca}}

DELETE http://localhost:3000/api/marca/{{idToDelete}}