### GET ALL
GET http://localhost:3000/api/marca

### POST
# @name createMarca
POST http://localhost:3000/api/marca
Content-Type: application/json

{
    "nombreMarca": "Loreal"
}

###ID
@id = {{createMarca.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/marca/{{id}}

### PUT
PUT http://localhost:3000/api/marca/{{id}}
Content-Type: application/json

{
    "nombreMarca": "Loreal"
}

# ### POST 2
# POST http://localhost:3000/api/marcas
# Content-Type: application/json

# {
#     "name": "Death Star",
#     "description": "Planet killer"
# }

### POST
# @nombreMarca createItemToDelete
POST http://localhost:3000/api/marca
Content-Type: application/json

{
    "nombreMarca": "Revlon",
}

### DELETE
//@idToDelete = {{createItemToDelete.response.body.data.idMarca}}

//DELETE http://localhost:3000/api/marca/{{idToDelete}}