### GET ALL
GET http://localhost:3000/api/turno

### POST
# @name createTurno
POST http://localhost:3000/api/turno
Content-Type: application/json

{
    "fechaHora": "2025-08-04T12:00:00Z",
    "estado": "pendiente",
    "atencion": 1
}

### ID
@id = {{createTurno.response.body.data.idTurno}}

### GET ONE
GET http://localhost:3000/api/turno/{{id}}

### PUT
PUT  http://localhost:3000/api/turno/{{id}}
Content-Type: application/json

{
  "fechaHora": "2025-08-04T12:00:00Z",
  "estado": "finalizado",
  "atencion": 1
}

### POST TURNO TO DELETE
# @name createTurnoToDelete
POST http://localhost:3000/api/turno
Content-Type: application/json

{
  "fechaHora": "2004-07-03T12:00:00Z",
  "estado": "pendiente",
   "atencion": 1
}

### DELETE
@idToDelete = {{createTurnoToDelete.response.body.data.idTurno}}
DELETE http://localhost:3000/api/turno/{{idToDelete}}