### GET ALL
GET http://localhost:3000/api/atencion

### POST
# @name createAtencion
POST http://localhost:3000/api/atencion
Content-Type: application/json

{
    "estado": "pendiente",
    "servicios": [1] ,
    "cliente": 3 ,
    "peluquero": 1,
    "descuentos": [1, 2]
}

###ID
@id = {{createAtencion.response.body.data.idAtencion}}

### GET ONE
GET http://localhost:3000/api/atencion/{{id}}

### PUT
PUT http://localhost:3000/api/atencion/{{id}}
Content-Type: application/json

{
    "estado": "finalizado",
    "servicios": [3] ,
    "cliente": 3 ,
    "peluquero": 1,
    "descuentos": [1, 2]
}


### POST
# @name createAtencionToDelete
POST http://localhost:3000/api/atencion
Content-Type: application/json

{
    "estado": "pendiente",
    "servicios": [2] ,
    "cliente": 1 ,
    "peluquero": 1,
    "descuentos": [1, 2]
}

### DELETE
@idToDelete = {{createAtencionToDelete.response.body.data.idAtencion}}

DELETE http://localhost:3000/api/atencion/{{idToDelete}}