### GET ALL
GET http://localhost:3000/api/pago

### POST
# @name createPago
POST http://localhost:3000/api/pago
Content-Type: application/json

{
    "fechaHora": "2025-08-04T12:00:00Z",
    "estado": "pendiente",
    "atencion": 1
}

### ID
@id = {{createPago.response.body.data.nroPago}}

### GET ONE
GET http://localhost:3000/api/pago/{{id}}

### PUT
PUT  http://localhost:3000/api/pago/{{id}}
Content-Type: application/json

{
  "hora": "12:00",
  "fecha": "2004-07-03",
  "estado": "pendiente"
}

### POST PAGO TO DELETE
# @name createPagoToDelete
POST http://localhost:3000/api/pago
Content-Type: application/json

{
  "fechaHora": "2004-07-03T12:00:00Z",
  "estado": "pendiente",
   "atencion": 1
}

### DELETE
@idToDelete = {{createPagoToDelete.response.body.data.nroPago}}
DELETE http://localhost:3000/api/turno/{{idToDelete}}