### GET ALL
GET http://localhost:3000/api/categoria

### POST
# @name createCategoria
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
    "nombreCategoria": "shampoo"
}

###ID
@id = {{createCategoria.response.body.data.idCategoria}}

### GET ONE
GET http://localhost:3000/api/categoria/{{id}}

### PUT
PUT http://localhost:3000/api/categoria/{{id}}
Content-Type: application/json

{
    "nombreCategoria": "shampoo"
}


### POST
# @name createCategoriaToDelete
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
    "nombreCategoria": "shampoo"
}

### DELETE
@idToDelete = {{createCategoriaToDelete.response.body.data.idCategoria}}

DELETE http://localhost:3000/api/categoria/{{idToDelete}}