### GET All 
GET http://localhost:3000/api/precio/servicio

### POST
# @name createservicio
POST http://localhost:3000/api/precio/servicio
Content-Type: application/json

{
    "nombreServicio": "balayage",
    "tiempoDemora": 60,
    "productos": [1, 2],
    "tonos": [1]
}

### ID
@idServicio = {{createservicio.response.body.data.codServicio}}

### GET ONE
GET http://localhost:3000/api/servicio/{{idServicio}}

### PUT
PUT  http://localhost:3000/api/servicio{{idServicio}}
Content-Type: application/json

### POST
# @name createservicioToDelete


@idToDelete = {{createservicioToDelete.response.body.data.codServicio}}
{
    "nombreServicio": "corte",
    "tiempoDemora": 30,
    "productos": [1, 2],
    "tonos": []
}

### DELETE
DELETE http://localhost:3000/api/servicio{{idToDelete}}


