### GET All 
GET http://localhost:3000/api/precio/servicio

### POST
# @name createservicio
POST http://localhost:3000/api/precio/servicio
Content-Type: application/json

{
    "nombreServicio": "balayage",
    "tiempoDemora": 60
}

### ID
@idServicio = {{createservicio.response.body.data.codServicio}}

### GET ONE
GET http://localhost:3000/api/servicio/{{idServicio}}

### PUT
PUT  http://localhost:3000/api/servicio{{idServicio}}
Content-Type: application/json

### DELETE
# @name createservicioToDelete
@idToDelete = {{createservicioToDelete.response.body.data.codServicio}}
DELETE http://localhost:3000/api/servicio{{idToDelete}}


